name: Test Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create simple HTML
      run: |
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>ESP32数据测试</title>
        </head>
        <body>
            <h1>✅ 工作流运行成功！</h1>
            <p>当前时间: <span id="time"></span></p>
            <script>
                document.getElementById('time').textContent = new Date().toLocaleString();
            </script>
        </body>
        </html>
        EOF
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
